print('Kimchi and Sausage Pizza\n')
print('Nutritional Facts:\n')
print('Calories:593', 'Fat:21g', 'Carbs:78g', 'Protein:22g', sep='~~~')
print('Preparation Time: 10 minutes\nCook Time: 20 minutes\nTotal Time: 30minutes\n')
servings = float(input('How many servings do you want to make? '))

pizza_dough = (servings / 2)
napa_cabbage_kimchi = (servings * 2)
marinara = (servings * .25)
shredded_mozz = (servings * .25)
sausage = (servings * 2)

print('Ingredients:\n')
print(f'{pizza_dough:.1f} Pound(s) Pizza Dough (homemade or store-bought')
print(f'{napa_cabbage_kimchi:.1f} ounces Napa Cabbage Kimchi')
print('All Purpose Flour (for dusting)')
print('Cornmeal (for dusting)')
print(f'{marinara:.1f} cup(s) Marinara (homemade or store-bought)')
print(f'{shredded_mozz:.1f} cup(s) Shredded Mozzarella')
print(f'{sausage:.1f} ounces Crumbled Italian Sausage')
print('Fresh Basil leaves\n')


print('Cooking Instructions:\n')
print('Prepare the Pizza Dough:\nIf the dough is refrigerated, let it come to room temperature on your counter for about one hour. Divide the dough in half, place both halves in a large bowl,\nand cover the bowl with plastic wrap to keep the dough from drying out.\n')
print('Preheat the Pizza Stone or Sheet pan:\nPosition the oven rack in the center of the oven, and place a pizza stone or large sheet pan on it. Preheat the oven to 500°F for at least 30 minutes so that\nthe pizza stone gets really hot.\n')
print('Prepare the Kimchi:\nRoughly chop the kimchi into 1/4-inch pieces. Using your hands (wear food-safe gloves, if you wish), squeeze the juices out of the kimchi so the dough doesn’t get\nsoggy. (Don’t toss the liquid! Make this stew with it.) \n')
print('Roll out the Pizza Dough:\nDust your counter top lightly with flour. Working with one portion (1 pound) of dough at a time, use a rolling pin to roll it into a 10- to 12-inch circle. You can\nalso spread the dough out with your fingers. Don’t stress about being precise with the size or shape. It doesn’t have to be a perfect circle! \n')
print('Prepare the Pizza peel:\nSpread a thin layer of cornmeal on your pizza peel and place the rolled-out dough on top. \n')
print('Top the pizza:\nSpoon half of the marinara sauce on the dough and evenly spread it to the outer edges with the back of a spoon. Sprinkle half of the cheese over the sauce.\nEvenly distribute half of the sausage and squeezed kimchi.\n')
print('Bake the Pizza:\nCarefully sprinkle some cornmeal onto the preheated pizza stone. Slide the pizza onto it and bake for 8 to 10 minutes, until the crust is golden brown and the\nsausage is cooked through. While the first pizza cooks, assemble the second pizza with the remaining ingredients.\n')
print('Cool slightly and serve:\nRemove the pizza from the oven, transfer it onto a cutting board and let it cool for a couple of minutes. Sprinkle with fresh basil, if you wish, and serve.\nBake the second pizza while you enjoy the first one.\n')
print('Enjoy!')

